default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: <%= ENV['DB_SOCKET'] %>

development:
  <<: *default
  database: maimai_blogchecker_development

test:
  <<: *default
  database: maimai_blogchecker_test

production:
  <<: *default
  database: maimai_blogchecker_production
